### ISSUE TITLE
html content as title or text does not parse

### ISSUE THREAD

**Issue by mayurbaldha** [june1249/ionic-super-popup#1]
`ionicSuperPopup.show("Success!", "<p>WWF has goal to: <q>Build a future where people live in harmony with nature.</q></p>", "success");`

**Comment by june1249** [comment]
Syntax error.
You can not use another quotation mark inside quotes.
If you want to use it, you can either change the quotes to **&#34;** or use **\** before the quotes.
Example: \"Build a future where people live in harmony with nature. \"

**Comment by june1249** [comment]
Syntax error.
You can not use another quotation mark inside quotes.
If you want to use it, you can either change the quotes to \ before the quotes.
Example:\\"Build a future where people live in harmony with nature.\\"

**Comment by mayurbaldha** [comment]
I actually wanted to add html content in .

e.g.

`ionicSuperPopup.show("Success!", "<div class='card'><p>WWF has goal to: <q>Build a future where people live in harmony with nature.</q></p></div>", "success");`

**Comment by june1249** [comment]
Default configuration has html set to false.
```
ionicSuperPopup.show({
    title: "Success!",
    text: "<div class='card'><p>WWF has goal to: <q>Build a future where people live in harmony with nature.</q></p></div>"
    type: "success",
    html: true
});
```
